name: all_validations_br
description: String validations and remover char ex ('/', '-', '.'), more than a validation for your best projects. Made with love
version: 3.0.0
homepage: https://github.com/CriandoGames/all_validations_br

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

