name: all_validations_br
description: "A powerful library Dart library for advanced validations: CPF, CNPJ, URLs, passwords, string checks, and character removal. Simplify your Dart and Flutter projects."
version: 3.1.1
homepage: https://github.com/CriandoGames/all_validations_br

environment:
  sdk: ">=2.16.0 <3.20.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter




