name: all_validations_br
description: A powerful library for string validations, including the removal of special characters (e.g., '/', '-', '.'), and advanced validation features to enhance your projects. Designed with precision and crafted with love.
version: 3.1.1
homepage: https://github.com/CriandoGames/all_validations_br

environment:
  sdk: ">=2.16.0 <3.20.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter




