name: all_validations_br
description: String validation and remover char ex ('/', '-', '.'), your validations for yours projects. mode with love
version: 1.1.2
homepage: https://github.com/CriandoGames/all_validations_br

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

