name: all_validations_br
description: String validations and remover char ex ('/', '-', '.'), more than a validation for your best projects. Made with love
version: 2.3.0
homepage: https://github.com/CriandoGames/all_validations_br

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

